project:
  type: book
  output-dir: docs

execute: 
  freeze: auto

book:
  title: "Blueprint Big Book of Data Analysis"
  comments: 
    giscus: 
      repo: context-dependent/bp-big-book
  reader-mode: true
  page-footer: 
    left: |
      The Blueprint Big Book of Data Analysis is an ongoing project
      led by the members of Blueprint Data Lab. 
  author: "Thomas McManus"
  date: "2023-04-28"
  chapters:
    - index.qmd
    - intro.qmd

    - part: wf.qmd
      chapters: 
        - wf-git.qmd
        - wf-structure.qmd
        - wf-basic.qmd
        - wf-getting-help.qmd
        - wf-goal.qmd
        - wf-pilots.qmd
    
    - part: viz.qmd
      chapters:
        - viz-why.qmd
        - viz-how.qmd
        - viz-gallery.qmd
    
    - part: sd.qmd
      chapters: 
        - sd-courses.qmd
        - sd-books.qmd

    - references.qmd

bibliography: references.bib

format:
  html:
    theme: 
      - cosmo
      - bpbb.scss
    code-link: true
    callout-appearance: simple

editor: visual


